version: "3"

services:
  broker:
    image: confluentinc/cp-kafka:7.0.9
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    # 컨테이너 안에서 호스트의 네트워크를 그대로 사용
    network_mode : host

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.9
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode : host

  python-kafka:
    build: 
      context: ./python-kafka
      dockerfile: Dockerfile
    container_name: python-kafka
    image: python-kafka:1.0
    volumes:
      - .:/app
    depends_on:
      - broker
    environment:
      KAFKA_BROKER: broker:9092
    network_mode : host
